// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import 'quasar/dist/types/feature-flag';
import { BrowserWindow } from 'electron';

declare module 'quasar/dist/types/feature-flag' {
  interface QuasarFeatureFlags {
    electron: true;
  }
}

declare global {
  namespace NodeJS {
    interface Global {
      __: NodeRequire;
      win: BrowserWindow;
      __statics: string;
    }
  }
}
